theme: jekyll-theme-cayman

name: Miguel
description: Web Developer
avatar: https://github.com/miguelzeph/minhapagina/blob/gh-pages/img/eu_githubpages.jpeg

# ProBot Request Info (https://probot.github.io/apps/request-info/)

requestInfoReplyComment: >
  ðŸ‘‹ We would appreciate it if you could provide us with more information about this
  issue. <br><br> ![](https://feross.net/x/cats/14.gif)
requestInfoLabelToAdd: 'need more info'

# ProBot Welcome (https://probot.github.io/apps/welcome/)

newPRWelcomeComment: >
  ðŸ™Œ Thanks for opening this pull request! You're awesome.
  <br><br> ![](https://feross.net/x/cats/6.gif)
firstPRMergeComment: >
  ðŸŽ‰ Congrats on getting your first pull request landed! <br><br>
  ![](https://feross.net/x/cats/29.gif)
